# key.properties (Keep safe, never commit to git public repository!)
# Place your release keystore (.jks) file inside the /android folder of this project.
keyAlias=ruhamaa_alias
keyPassword=RuhamaaSecurePassword123!
storeFile=ruhamaa_release_key.jks
storePassword=RuhamaaSecurePassword123!
